# Generated by Django 2.2.7 on 2019-11-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
