# Generated by Django 2.2.7 on 2019-11-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20191127_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user_socre',
            new_name='user_score',
        ),
    ]
