# Generated by Django 2.2.7 on 2019-11-27 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0003_auto_20191127_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='score_users',
            field=models.ManyToManyField(related_name='score_series', through='series.Score', to=settings.AUTH_USER_MODEL),
        ),
    ]
