# Generated by Django 2.2.7 on 2019-11-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
