# Generated by Django 2.2.7 on 2019-11-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191121_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Series'),
            preserve_default=False,
        ),
    ]
